apiVersion: v1
kind: Namespace
metadata:
  name: forgejo-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-deployer
  namespace: forgejo-system
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-deployer-token
  namespace: forgejo-system
  annotations:
    kubernetes.io/service-account.name: forgejo-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forgejo-deployer
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - persistentvolumeclaims
      - serviceaccounts
      - namespaces
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

  - apiGroups: ["traefik.io"]
    resources:
      - "ingressroutes"
      - "middlewares"
      - "traefikservices"
      - "serverstransport"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - "servicemonitors"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forgejo-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forgejo-deployer
subjects:
  - kind: ServiceAccount
    name: forgejo-deployer
    namespace: forgejo-system
