apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-dns-api-token
          stringData:
            cloudflare-dns-api-token: ENC[AES256_GCM,data:ywbYpsh4ZAiclPfdQqsKXQCtr2PXo3vawX8EubB5t1LIrFx0JpTNIA==,iv:o7+7RgFDqg6igMXKMlQ6Apy8RFH/KPGwaKItUTGJUZ8=,tag:1SK9SDOkWYWavhDJ8iUGsA==,type:str]
sops:
    age:
        - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaktxcHBWMFFnNG1SVGsw
            MVZVa0hpZmNmVkJtTldLOUx3TUQwT1UwSUJjCk1YeG9RbkpxSEFpSTg3R1krZW1Q
            aWtZdXo3am9Ic01BbW5MaitPOUpBZlEKLS0tIC9ock0wYVpxNUxiaXc3SitraWtV
            RFNMaUJtcGwvSk1rbERIeUlpcmNjcXMKuwgLsaTh3PI6t39tLUn/3lrddPhFL9t/
            IaH1evLthTnUQSitI/4ZIqP4Q3FAPiWiLpNRpOcjSqLrn2VEUPwLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T03:11:24Z"
    mac: ENC[AES256_GCM,data:c0Wwf08EWlrF18jdX4krUSIPHaOmXrRT96A4uImxa6lSkwI+C9ATqBxoh49gxsKdjpJUCiesiKa/m9EvaMiSfH/tjt5QvP9qoOEGrFitNMcU2IdJLIzKOpIkRywglhrMjV3Huuo1KqvVRtP7O1prxdGsOz/ShBNjEEyXk+Rl/IY=,iv:N0TnIaqztGpa1iMnqpYHfVOJFwk6Yt751S5DX76ssVY=,tag:cnWRGFJ5MaeAEeeAGn3Mcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
