# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/isindir.github.com/sopssecret_v1alpha3.json
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: db-roles
    namespace: databases
spec:
    secretTemplates:
        - name: vaultwarden-db
          labels:
            cnpg.io/reload: "true"
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: vaultwarden
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: vaultwarden
          stringData:
            username: ENC[AES256_GCM,data:cXrnbP3u2rSAHFc=,iv:YrpdBDzLbi8k1ozn820MDWOSWemx8aPT5DsLpYWRJRw=,tag:3n9m09ZPpohscXqQjxax/Q==,type:str]
            password: ENC[AES256_GCM,data:uc/ifiz0RIK0qXHi,iv:RoRpKrHfgYRgRfDB4aU2/mManpJ9s1DxmRAr60A3yCc=,tag:ILDlXOq4Ozqh4ukdmUfN+A==,type:str]
          type: kubernetes.io/basic-auth
        - name: forgejo-db
          labels:
            cnpg.io/reload: "true"
          stringData:
            username: ENC[AES256_GCM,data:/e9FauvYDQ==,iv:paPep2GafserfYy7suuRnFMMEIAB/wom8lfplOm5Hzk=,tag:hjquXH1RGDLriHQS1o/0+A==,type:str]
            password: ENC[AES256_GCM,data:H+cZ10zyWoj/td3ihPIfrg==,iv:KrvXw211c9xkTdbgXzSAHB8/Ev/l0rpaE2ev1/BmfNw=,tag:fF1o5x2lx5vLD4CreSU5nw==,type:str]
sops:
    age:
        - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZFBLV2ZCU1hMb1VIaGJR
            bGprVmhyU1RrclNaamVaUjU3d0d6SERoeTJJCm1FNFI3NE9odUFoU3cwQVlCM0Ix
            SkNQZENuRHZVY1NLb0I2VEtXUmhBQ3MKLS0tIERnS2R4OTN5WkRNUmE3dVFKbEd3
            YTZwSitoQTdIS2xMVm9iN2lHYjlQZ0kKpYRflwZ/Wa086prNhjPSiVbpmlUab2ih
            lQdhUz2gFb0ObQ4ZIkIvkWPF+k59otOXTQGfOIR8Dx6sc77/kcBSIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T00:21:40Z"
    mac: ENC[AES256_GCM,data:JTVzJ+th4O0oNM6paSE2u31ns9U6Q8DuJsvDr5ZW29tTDtQI9HZQIp4w0Eu0g3gjI7YqHAqn40QP04uZEQfHWps3Vq4cqoetNzXBhtFqnpx0o4oDmP9WIx8AqSyLC/9XSmYrnoIZJvR/YZc+/SqPDYEjWj5dqNxooyaEB22bmBQ=,iv:FFVq/hqxyTtegOP/5Fx4sIVr0me+iXuNQsVZ5lSCpuA=,tag:D9MPOCUsizBDsGYZi4SXpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
