# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/isindir.github.com/sopssecret_v1alpha3.json
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: db-roles
  namespace: databases
spec:
  secretTemplates:
    - name: vaultwarden-db
      labels:
        cnpg.io/reload: "true"
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "vaultwarden"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "vaultwarden"
      stringData:
        username: ENC[AES256_GCM,data:cXrnbP3u2rSAHFc=,iv:YrpdBDzLbi8k1ozn820MDWOSWemx8aPT5DsLpYWRJRw=,tag:3n9m09ZPpohscXqQjxax/Q==,type:str]
        password: ENC[AES256_GCM,data:uc/ifiz0RIK0qXHi,iv:RoRpKrHfgYRgRfDB4aU2/mManpJ9s1DxmRAr60A3yCc=,tag:ILDlXOq4Ozqh4ukdmUfN+A==,type:str]
      type: kubernetes.io/basic-auth
sops:
  age:
    - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZFBLV2ZCU1hMb1VIaGJR
        bGprVmhyU1RrclNaamVaUjU3d0d6SERoeTJJCm1FNFI3NE9odUFoU3cwQVlCM0Ix
        SkNQZENuRHZVY1NLb0I2VEtXUmhBQ3MKLS0tIERnS2R4OTN5WkRNUmE3dVFKbEd3
        YTZwSitoQTdIS2xMVm9iN2lHYjlQZ0kKpYRflwZ/Wa086prNhjPSiVbpmlUab2ih
        lQdhUz2gFb0ObQ4ZIkIvkWPF+k59otOXTQGfOIR8Dx6sc77/kcBSIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T21:59:21Z"
  mac: ENC[AES256_GCM,data:/qi5QwpCfxN+XkCe/6xHuWDlshN/DAcAoMZyXPcXlmswFRwvKKnYiLcNNI9fxjdR+nNlqRgKGYniIpGt0JzgmzDjJPAMuDqbvZALtbl8cO3SGMcMoX6FL+yj3hN/EUH7xPNCumb+ItpofN8ntbrVtxtKb70kpPRIXzFoteLQSNE=,iv:m6yGHg7tEuhdUlwsa1AW+HGkFN8EczBmzpdJ4LFShtk=,tag:+AT7+Hw/8Cd0aHszdXtLNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
