apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-secrets
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-app-ini-db
          labels:
            cnpg.io/reload: "true"
          stringData:
            database: ENC[AES256_GCM,data:Cx/wQ+HxDldm5HhONSBnoW6BvLF9fE6x0YEzt8CiI19HW7yXXJ1jvqVXAwmkBqOq7MDTD5OlrVo/W0/cay4h8YU7OdW2TcQXWQfO4S3vbauN+IUrow91+7nhcZ780QIfE9HgvAvK4I4=,iv:Ed8+tbkw2ULlUZ9Q7fZoNBa2+xP37F54CWjwjXWYqrc=,tag:JTBUmzEQb2Y36/jdcaNXhA==,type:str]
        - name: forgejo-admin-secret
          stringData:
            username: ENC[AES256_GCM,data:OvDT9und,iv:fvDF9/oqTR591pmFFaerH+xuOoGumguL0k98Cg457/s=,tag:75egf5g6P/bfT+6p0VkLCw==,type:str]
            password: ENC[AES256_GCM,data:EvpCCZtjLEUpZTBmuzA=,iv:4LjgV0sXoHbuaOdV9UDIwKhMEYYZesRn75ZgHY6kXOs=,tag:RE+34R7SQ7MC/chJbQJ0fw==,type:str]
            email: ENC[AES256_GCM,data:dZRrr1ASDQNspMk0pjf6lxMXDq2X89A=,iv:OsG/goPXk0k5AqEunXzXRoE2+NYOcoewWeXc4eVFe4c=,tag:lVkJgxVbnVsVPw9IM7RJAg==,type:str]
sops:
    age:
        - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQVIrbDhEYnIzNHRrOVd1
            clQ4eTB3YnBQN1lqWjl3SnJLVFlYd3ovM0FRCkdCb2pVMjZuc2JVUWM0TWhQUHVL
            N29OWU54MGVoTFlyd1hLb1J3M1grNzQKLS0tIG9wazhQdTdFbnZoK1M3WlZKdFda
            d0E1bVdCWVU4bTlMS0wzNnJmZWFHNGMKw+L31Rk3LorE2t1D38KVIQQ/V98YJQKk
            m1tjEEkfUViLnromoT0YnqK7LP+T/YLvfVDGAKXy/pUEPW7ex6MXwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T00:42:01Z"
    mac: ENC[AES256_GCM,data:4bdFaOc+FR46JHg6F0D4n1kCBaWBjFC4ZLM1J8oWRMvhzyovgxO8Wj+3Re4pDC9AGYlZ45XaeGqPbNwOJF9zlHCQgtqFyCbPDsAG8Qsr/MO5CppWtgT1jYxfza79vpKq4lBLG75iPMHJP0CKpfDTymWKaTIsh4WSBv717oVaLqk=,iv:zOuCgVErpcKKQPyKa8AkfCjzLcd6LDi0K1SsYGPUAUA=,tag:0FSicHGJwICIh5F0/LpXkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
