# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/isindir.github.com/sopssecret_v1alpha3.json
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            username: ENC[AES256_GCM,data:1MbI+/1D,iv:Yevynh6a8eXZZn9duxaQ0gMEud39japujXSlJZO9aoQ=,tag:EPL3bf6mwzZFlbMvYF9Oxg==,type:str]
            password: ENC[AES256_GCM,data:bapylzAJspF5WFPEZ8Q=,iv:c5Rf5C+yU3JMLE86MsR+t7lZS+/C4KZfK8/I1Mk5CbY=,tag:/samT5drTqo598YICdL/Xw==,type:str]
sops:
    age:
        - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVk1WdXY2M0sxbjlEMmUz
            SVZyOGN4WnJLZG1JZERNQXBvOEM2UXJaeHhRCjNiZE9obGwzM2ZaSDJGMVY2UjFC
            ZDFDZXBBVGFIaUluQXFEdHJEWTc0REEKLS0tIFhLcU5MZE56RzgwM2xuRDVoK0FF
            ODhVRmlVVVE2cVRrU0N2R0tXSEk5R1EKsA3Ah88OTt2JL7w20epR7ylqjxA6OY8u
            k97EpBdqBmXkIAtjSBlMQb+0ke9GARb32dLieut38l+4yFtekaUMDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:22:47Z"
    mac: ENC[AES256_GCM,data:HxwaB5HzJxgd+M1BN8EpVEid/GCEg05O+iuHAgufhYBvq84/ZGBmrdG0iFY87End9m0xIJZioq9+IObXHM3IxeCspMQYba4bJJzZX3yI7wQq5SYeV9va34jmRfT44X0NSVdLHLX3SIb6ppLZPKWkHSQ40sucvdGwyeTS2P5ary8=,iv:HOUkENdkoixCboxagDZpJrZI9Pf5pn1ac2llwa3MgSw=,tag:2AN/jlqyg1oeLAR74Lrk+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
