apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  secretTemplates:
    - name: vaultwarden-admin-token
      stringData:
        token: ENC[AES256_GCM,data:STEqnJwgmh7k8hFnKKoloJuqxYSSebIurvKfRM/U3XGpt2kSB16DrMpoLU9h7yzElgNrMJujqVTZ1LmQtYSIwQ==,iv:WFXg/m0KMGsygbDHRPyf/xqDlm3+MB9TdLafuOoYAiY=,tag:OuL3g5GVnmWhUQEObG5GZw==,type:str]
sops:
  age:
    - recipient: age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQkdDSHVVRmt1NmtrOTlR
        M21DWkxNTERqOEUvRmVNcnRpMkcxNnAzYm5FClpiZ0tLZzdaV3RMcVVTNktFZnZR
        aE9sN1RUOElxNHdNU1BYdldsck9pelkKLS0tIFRIbjRJNWpRR0hMUU5weDBFMldD
        NktUNlFVcVgxVWt0QXd1WHJyZExPTWMKJkzpoK4L/rwZmunuAg3bBS1XIbV+9PaI
        5Q/PC763ICoy6yk+n3JHupwEyYfFuroR700YmG1f+3bO6IPuI6uTvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T22:22:05Z"
  mac: ENC[AES256_GCM,data:6AtVc5lrOwXqoHTALoCdoDvXtiapRF/cMFm1Zs9bU4cOD5O7BtztL4Em858G9m5I+S0KDI9jm8SDJQqgDHnsKxhNF1ggw3OODhl5d/hnlboSZg5ymwmwPKfqkkx7v+msuhN2/7l6IJ2ra98yIS4k/1YoMPbvrcGjnzPEbw3amF4=,iv:jAVlcKdd740nscEiMIUpT758fbupgmqEGra8f6ftm0I=,tag:INJY9Tl1f9rfqr+NPuo3gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
