# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: trusted-only
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 10.10.0.0/16 # LAN subnet
      - 10.20.0.0/16 # trusted clients subnet
