repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: emberstack
    url: ghcr.io/emberstack/helm-charts
    oci: true
  - name: sops
    url: https://isindir.github.io/sops-secrets-operator
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: prometheus-community
    url: ghcr.io/prometheus-community/charts
    oci: true
  - name: rocm
    url: https://rocm.github.io/gpu-operator

releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    createNamespace: true
    values:
      - ./metallb/values.yaml

  - name: longhorn
    chart: longhorn/longhorn
    namespace: longhorn-system
    createNamespace: true
    values:
      - ./longhorn/values.yaml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    createNamespace: true
    version: 1.19.1
    values:
      - ./cert-manager/values.yaml

  - name: traefik-crds
    chart: traefik/traefik-crds
    namespace: traefik
    createNamespace: true

  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    createNamespace: false
    needs:
      - traefik/traefik-crds
    values:
      - ./traefik/values.yaml

  - name: reflector
    chart: emberstack/reflector
    namespace: reflector
    createNamespace: true
    version: 9.1.39

  - name: sops
    chart: sops/sops-secrets-operator
    namespace: sops
    createNamespace: true
    values:
      - ./sops/values.yaml

  - name: cloudnative-pg
    chart: cnpg/cloudnative-pg
    namespace: cnpg-system
    createNamespace: true
    values:
      - ./cloudnative-pg/values.yaml

  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    version: 79.5.0
    values:
      - ./kube-prometheus-stack/values.yaml

  - name: amd-gpu-operator
    chart: rocm/gpu-operator-charts
    namespace: kube-amd-gpu
    createNamespace: true
