repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    createNamespace: true
    values:
      - ./metallb/values.yaml

  - name: longhorn
    chart: longhorn/longhorn
    namespace: longhorn-system
    createNamespace: true
    values:
      - ./longhorn/values.yaml
