---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: apps
spec:
  type: ExternalName
  externalName: 10.25.1.1
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/ingressroute_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress-route
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home-assistant.apps.chesurah.net`)
      services:
        - name: home-assistant
          namespace: apps
          port: 8123
  tls:
    secretName: apps-chesurah-net-prod-tls
