# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/ingressroute_v1alpha1.json
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress-route
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.infra.chesurah.net`)
      middlewares:
        - name: trusted-only
          namespace: traefik
      services:
        - name: kube-prometheus-stack-prometheus
          namespace: monitoring
          port: 9090
  tls:
    secretName: infra-chesurah-net-prod-tls
