# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.12.2.1-10.12.2.254
  autoAssign: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/metallb.io/l2advertisement_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool
