---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jburke.create@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: jburke.create@gmail.com
            apiTokenSecretRef:
              name: cloudflare-dns-api-token
              key: cloudflare-dns-api-token
        selector:
          dnsZones:
            - "chesurah.net"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jburke.create@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: jburke.create@gmail.com
            apiTokenSecretRef:
              name: cloudflare-dns-api-token
              key: cloudflare-dns-api-token
        selector:
          dnsZones:
            - "chesurah.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testing-chesurah-net
  namespace: cert-manager
spec:
  secretName: testing-chesurah-net-staging-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.testing.chesurah.net"
  dnsNames:
    - "testing.chesurah.net"
    - "*.testing.chesurah.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-chesurah-net
  namespace: cert-manager
spec:
  secretName: apps-chesurah-net-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.apps.chesurah.net"
  dnsNames:
    - "apps.chesurah.net"
    - "*.apps.chesurah.net"
