apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
provisioner: nfs.csi.k8s.io
parameters:
  server: colossus.home.chesurah.net
  share: /tank/media
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
  - rsize=1048576
  - rsize=1048576
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-downloads
provisioner: nfs.csi.k8s.io
parameters:
  server: colossus.home.chesurah.net
  share: /tank/downloads
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
  - rsize=1048576
  - rsize=1048576
reclaimPolicy: Retain
volumeBindingMode: Immediate
