# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: databases
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: postgres-ha
