apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-models
  namespace: ollama
data:
  ollama-host: "http://ollama-rocm-service:11434"
  reconciler-script.sh: |
    set -e
    apt-get update && \
    apt-get install -y \
      yq \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

    until curl -sf $OLLAMA_HOST/api/version > /dev/null; do
      echo "Waiting for Ollama service..."
      sleep 5
    done

    echo "=== Current models ==="
    ollama list || true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ollama-reconcile-models
  namespace: ollama
spec:
  schedule: "0 0 31 2 *" # never schedule
  suspend: true
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: reconciler
              image: ollama/ollama:rocm
              command: ["/bin/bash", "/config/reconciler-script.sh"]
              env:
                - name: OLLAMA_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: ollama-models
                      key: ollama-host
              volumeMounts:
                - mountPath: /config
                  name: config
                  readOnly: true
                - mountPath: /root/.ollama
                  name: ollama-data
          volumes:
            - name: config
              configMap:
                name: ollama-models
                items:
                  - key: "reconciler-script.sh"
                    path: "reconciler-script.sh"
