repositories:
  - name: vaultwarden
    url: https://guerzon.github.io/vaultwarden
  - name: forgejo
    url: code.forgejo.org/forgejo-helm
    oci: true

releases:
  - name: vaultwarden
    chart: vaultwarden/vaultwarden
    namespace: vaultwarden
    createNamespace: true
    values:
      - ./vaultwarden/values.yaml
  - name: forgejo
    chart: forgejo/forgejo
    namespace: forgejo
    version: 15.0.3
    values:
      - ./forgejo/values.yaml
