# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/ingressroute_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo-ingress-route
  namespace: forgejo
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`forgejo.apps.chesurah.net`)
      services:
        - name: forgejo-http
          namespace: forgejo
          port: 3000
  tls:
    secretName: apps-chesurah-net-prod-tls
